name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use your preferred Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build your Astro site
      - name: Build Astro site
        run: npm run build

      # Step 5: Add .nojekyll to disable Jekyll processing on GitHub Pages
      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      # Step 6: Create CNAME file for your custom domain
      - name: Create CNAME file
        run: echo "gcmarais.com" > dist/CNAME

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: gcmarais.com
