name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches:
      - main  # This is the source branch where your code lives

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build your Astro site (make sure your package.json has "build": "astro build")
      - name: Build Astro site
        run: npm run build

      # 5. Disable Jekyll by adding a .nojekyll file to the build output
      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      # 6. Create a CNAME file with your custom domain
      - name: Create CNAME file
        run: echo "gcmarais.com" > dist/CNAME

      # 7. Deploy the built site to the dedicated branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  # Updated to use a dedicated deployment branch
          cname: gcmarais.com
