name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js (choose your preferred Node version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Change this if needed

      # 3. Install dependencies using a clean install
      - name: Install Dependencies
        run: npm ci

      # 4. Fix the Astro binary permissions (resolves "Permission denied" issues)
      - name: Fix Astro Binary Permissions
        run: chmod +x ./node_modules/.bin/astro

      # 5. Build your Astro site (this will also copy your public/ folder including any CNAME file)
      - name: Build Astro Site
        run: npm run build

      # 6. Create a .nojekyll file in the build output to disable GitHub Pages’ Jekyll processing
      - name: Create .nojekyll file
        run: echo > dist/.nojekyll

      # 7. Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
